version: '3'

networks:
  backend:
    name: backend
    driver: bridge

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
      - db_data:/data
    networks:
      - backend
    links:
      - mariadb_database:mariadb_database
    depends_on:
      - mariadb_database

  mariadb_database:
    image: library/mariadb:latest
    expose:
      - $DB_PORT
    ports:
      - $DB_PORT:$DB_PORT
    container_name: $DB_DATABASE
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/data/
    networks:
      - backend
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database/mysql_data'
  node_modules: